### ISSUE TITLE
请问GA运行怎么填写secrets参数？

### ISSUE THREAD

**Issue by Blender-S** [kang0221/AutoSignMachine#4]
有多个手机号想要actions自动跑，但是不知道该怎么填secret中的多帐号参数，大佬能告知一下吗？谢谢啦！

**Comment by kang0221** [comment]
env:
        user: ${{secrets.unicom_user}}
        password: ${{secrets.unicom_password}}
        user2: ${{secrets.unicom_user2}}
        password2: ${{secrets.unicom_password2}}
        appid: ${{secrets.unicom_appid}}
yml里secrets开头的都需要在secrets中配置， key就是secrets后的变量名，如unicom_user、unicom_user2，值就是你的手机号那些
![image](https://user-images.githubusercontent.com/32613757/110618874-1e83c700-81d2-11eb-86bf-5c62e58e4a79.png)

**Comment by kang0221** [comment]
> 好的，谢谢，我研究一下，你做的这个真的太棒了

谢谢夸奖，我也是搬运大佬做的代码，修改了一些小报错而已。

**Comment by Blender-S** [comment]
我就是用另一个在终端跑的，尤其是那个检测200M很是烦人，我是不限流量限速套餐，没有流量包，它老是运行几个任务之后就不运行了，我又不会改代码，搜了一下，发现你这个了，而且还加了多账号，高兴啊，再次感谢您的分享

**Comment by leecheng310** [comment]
搭车问下钉钉推送怎么填写secrets

流传的各种版本各种报错，你这个各种修改一看就是用心了~
