### ISSUE TITLE
daily-task 这个 actions 运行出错

### ISSUE THREAD

**Issue by Blender-S** [kang0221/AutoSignMachine#5]
就是 actions 里那个 daily-task 运行参数带了 --tryrun，每隔一个小时就运行一次，但是会报错，这个是不是可以禁用掉呢？

任务配置文件不存在，创建配置中
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
tryRun模式忽略执行延迟
计算可执行任务 总任务数 47 已完成任务数 0 错误任务数 0 指定任务数 0 预计可执行任务数 47
开始执行任务
dailysignin: cookies凭据访问失败，将使用账户密码登录
dailysignin: 获得登录状态成功
dailyNotifyReward: 调度任务中 并发数 1
dailyNotifyReward: [❌🤣🌋] unicom任务: Error: ENOENT: no such file or directory, open '/home/runner/.AutoSignMachine/taskFile_unicom_***.json'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at Object.updateTaskFile (/home/runner/work/AutoSignMachine/AutoSignMachine/utils/scheduler.js:56:27)
    at Object.execTask (/home/runner/work/AutoSignMachine/AutoSignMachine/utils/scheduler.js:301:27)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/runner/work/AutoSignMachine/AutoSignMachine/commands/unicom.js:56:9
    at async run (/home/runner/work/AutoSignMachine/AutoSignMachine/node_modules/p-queue/dist/index.js:163:29) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/runner/.AutoSignMachine/taskFile_unicom_***.json'
}
dailyNotifyReward: 当前任务执行完毕！
![Screenshot_2021-03-12 Blender-S AutoSignMachine](https://user-images.githubusercontent.com/75414580/110940173-73117880-8371-11eb-831a-440163cb5269.png)

**Comment by kang0221** [comment]
> 就是 actions 里那个 daily-task 运行参数带了 --tryrun，每隔一个小时就运行一次，但是会报错，这个是不是可以禁用掉呢？
> 
> 任务配置文件不存在，创建配置中
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> tryRun模式忽略执行延迟
> 计算可执行任务 总任务数 47 已完成任务数 0 错误任务数 0 指定任务数 0 预计可执行任务数 47
> 开始执行任务
> dailysignin: cookies凭据访问失败，将使用账户密码登录
> dailysignin: 获得登录状态成功
> dailyNotifyReward: 调度任务中 并发数 1
> dailyNotifyReward: [❌🤣🌋] unicom任务: Error: ENOENT: no such file or directory, open '/home/runner/.AutoSignMachine/taskFile_unicom__**.json' at Object.openSync (fs.js:462:3) at Object.readFileSync (fs.js:364:35) at Object.updateTaskFile (/home/runner/work/AutoSignMachine/AutoSignMachine/utils/scheduler.js:56:27) at Object.execTask (/home/runner/work/AutoSignMachine/AutoSignMachine/utils/scheduler.js:301:27) at processTicksAndRejections (internal/process/task_queues.js:97:5) at async /home/runner/work/AutoSignMachine/AutoSignMachine/commands/unicom.js:56:9 at async run (/home/runner/work/AutoSignMachine/AutoSignMachine/node_modules/p-queue/dist/index.js:163:29) { errno: -2, syscall: 'open', code: 'ENOENT', path: '/home/runner/.AutoSignMachine/taskFile_unicom_**_.json'
> }
> dailyNotifyReward: 当前任务执行完毕！
> ![Screenshot_2021-03-12 Blender-S AutoSignMachine](https://user-images.githubusercontent.com/75414580/110940173-73117880-8371-11eb-831a-440163cb5269.png)

我就只开了多好签到的，其他都没开

**Comment by kang0221** [comment]
我只开了联通 多号签到的任务

**Comment by Blender-S** [comment]
我把这个任务给关闭，观察了一下确实没什么用
而且我看了最近两天的运行日志，有些任务出错，我手动在终端跑也跑不起来，不知道哪里的问题
难道官方改了任务api了？
